version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 6543:5432
    networks:
      - net
    volumes:
      - ./postgres/dbfiles/initPostgres.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    networks:
      - net
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  lyrics:
    container_name: lyrics
    build: ./sitio
    ports:
      - 8000:8000
    volumes:
      - ./sitio:/app
      - ./media:/app/media:rw
    networks:
      - net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: lyrics
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
      - pgadmin

  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    container_name: sonarqube
    depends_on:
      - postgres
      - pgadmin
      - lyrics
    networks:
      - net
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: qwerty
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/temp:/opt/sonarqube/temp
      - ./sonarqube/conf:/opt/sonarqube/conf

  jenkins:
    image: jenkins/docker
    build:
      context: ./jenkins
    ports:
      - 8081:8080
      - 50000:50000
    networks:
      - net
    container_name: jenkins
    depends_on:
      - sonarqube
      - pgadmin
      - lyrics
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  net:

volumes:
  postgres_dbfiles:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonarqube_conf:
  jenkins_home:
