version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 6543:5432
    networks:
      - net
    volumes:
      - ./postgres/dbfiles/initPostgres.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    networks:
      - net
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  lyrics:
    container_name: lyrics
    build: ./sitio
    ports:
      - 8000:8000
    volumes:
      - ./sitio:/app
    networks:
      - net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: lyrics
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
      - pgadmin

networks:
  net:

volumes:
  postgres_dbfiles:
  postgres_data:
