version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - net
    volumes:
      - ./postgres/dbfiles/initPostgres.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres
    networks:
      - net
    ports:
        - 9090:8080

  lyrics:
    container_name: lyrics
    build: ./sitio
    ports:
      - 8000:8000
    volumes:
      - ./sitio:/app
      - ./media:/app/media
    networks:
      - net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: lyrics
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
      - adminer

networks:
  net:

volumes:
  postgres_dbfiles:
  postgres_data:
